"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var jwt_1 = require("../middlewares/jwt");
var express_1 = require("express");
var video_1 = require("../middlewares/video");
var auth_1 = require("../middlewares/auth");
// import uploadsMiddleware from '../middlewares/video';
exports.router = express_1.default.Router();
exports.router.get('/login', jwt_1.default);
exports.router.get('/videos', auth_1.authMiddleware, video_1.getVideos);
exports.router.get('/videos/:id', auth_1.authMiddleware, video_1.getVideoById);
// router.post('/upload', authMiddleware, uploadsMiddleware.uploadVideo);
